name: build and deploy to s3

on:
  workflow_dispatch:
    inputs:
      site:
        description: "Select target site (デプロイするサイトのディレクトリ名をカンマ区切りで記入)"
        required: true

      environment:
        type: environment
        description: "Deploy environment"
        required: true

permissions:
  id-token: write # This is required for requesting the JWT (id token)
  contents: read # This is required for actions/checkout

jobs:
  build-and-deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js # TODO:必要なのかな？
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies # TODO:必要なのかな？
        run: npm install

      - name: convert to space format
        id: convert
        run: | # カンマ区切りの入力をスペース区切りに変換
          DIRECTORIES=$(echo '${{ github.event.inputs.site }}' | tr "," " ")
          echo "directories: $DIRECTORIES"
          echo "directories=$DIRECTORIES" >> "$GITHUB_OUTPUT"

      - name: Get label-specified directories and check existence
        id: directory_check
        run: | # 存在するディレクトリのみを取得
          TARGET_DIRECTORIES=""
          for directory in ${{ steps.convert.outputs.directories }}; do
            directory_path="sites/$directory"
            if [ -d "$directory_path" ]; then
              echo "Found directory: $directory_path"
              TARGET_DIRECTORIES="$TARGET_DIRECTORIES $directory"
            else
              echo "Directory $directory_path does not exist. Skipping."
            fi
          done
          echo "target_directories=$TARGET_DIRECTORIES" >> "$GITHUB_OUTPUT"

      - name: Fetch token
        uses: aws-actions/configure-aws-credentials@v4 # OIDC（IDトークン）を使用してAWS認証を行い、一時的な認証情報を取得
        with:
          # GitHub Actionsが引き受けるAWS IAMロールのARNを指定
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDC@site-build-environments-v2
          aws-region: ap-northeast-1

      - name: Build all found directories
        if: steps.directory_check.outputs.target_directories != ''
        run: | # 存在する各ディレクトリに対してビルドを実行
          for directory in ${{ steps.directory_check.outputs.target_directories }}; do
            echo "Building sites/$directory..."
            cd sites/$directory
            npm install
            npm run build
            cd -
          done

      - name: Deploy to s3
        if: steps.directory_check.outputs.target_directories != ''
        run: | # 存在する各ディレクトリに対してデプロイを実行
          for directory in ${{ steps.directory_check.outputs.target_directories }}; do
            bash .scripts/deploy-to-s3.sh $directory
          done
